In [1]:
import pandas as pd
import numpy as np
import seaborn as snsz

In [3]:
k=[4,6,2.56789,9,87.9999,40,'hyderabad']
k

[4, 6, 2.56789, 9, 87.9999, 40, 'hyderabad']

In [5]:
pd.Series(k)

0            4
1            6
2      2.56789
3            9
4      87.9999
5           40
6    hyderabad
dtype: object

In [10]:
 a=np.random.randint(20,50,(5,4))
a

array([[25, 38, 31, 38],
       [34, 48, 48, 35],
       [25, 23, 32, 32],
       [46, 23, 47, 20],
       [48, 47, 32, 46]])

In [12]:
a.ndim

2

In [44]:
b=np.random.randint(2,54,(8,4))
b

array([[14,  3, 27,  3],
       [34, 19, 28,  5],
       [47, 10,  9, 20],
       [20, 15, 41,  9],
       [24, 21, 38,  7],
       [39, 13, 24, 40],
       [ 6, 42, 44, 27],
       [37, 28, 38, 17]])

In [46]:
b.shape

(8, 4)

In [48]:
c=np.random.randint(2,54,
                    
                    15)
c

array([43, 24,  2, 17, 34, 31, 24, 38, 12, 16, 16,  7, 44, 47, 27])

In [50]:
pd.Series(c)

0     43
1     24
2      2
3     17
4     34
5     31
6     24
7     38
8     12
9     16
10    16
11     7
12    44
13    47
14    27
dtype: int32

In [52]:
c.shape

(15,)

In [54]:
df=pd.DataFrame(b)
df

0   1   2   3
0  14   3  27   3
1  34  19  28   5
2  47  10   9  20
3  20  15  41   9
4  24  21  38   7
5  39  13  24  40
6   6  42  44  27
7  37  28  38  17

In [56]:
g=pd.DataFrame(b,columns=['Roll','Name','age','Country'])
g

Roll  Name  age  Country
0    14     3   27        3
1    34    19   28        5
2    47    10    9       20
3    20    15   41        9
4    24    21   38        7
5    39    13   24       40
6     6    42   44       27
7    37    28   38       17

In [67]:
l=pd.DataFrame(b,index=[181,182,183,184,185,186,187,188])
l

0   1   2   3
181  14   3  27   3
182  34  19  28   5
183  47  10   9  20
184  20  15  41   9
185  24  21  38   7
186  39  13  24  40
187   6  42  44  27
188  37  28  38  17

In [69]:
j=pd.DataFrame(b,columns=['Roll','Name','age','Country'],index=[181,182,183,184,185,186,187,188])
j

Roll  Name  age  Country
181    14     3   27        3
182    34    19   28        5
183    47    10    9       20
184    20    15   41        9
185    24    21   38        7
186    39    13   24       40
187     6    42   44       27
188    37    28   38       17

In [75]:
j.iloc[3]

Roll       20
Name       15
age        41
Country     9
Name: 184, dtype: int32